/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Sales;

import javax.swing.JPanel;


import model.Business.Business;


/**
 *
 * @author martta
 */
public class SalesWorkArea extends javax.swing.JPanel {
    private Business business;
    private JPanel userProcessContainer;

    /**
     * Creates new form SalesWorkArea
     */
    public SalesWorkArea(Business business,JPanel userProcessContainer) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSales = new javax.swing.JLabel();
        BtnViewSupplierReport = new javax.swing.JButton();
        BtnViewCustomerReport = new javax.swing.JButton();
        BtnViewRevenueReport = new javax.swing.JButton();
        BtnManagePrice = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        lblSales.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblSales.setForeground(new java.awt.Color(255, 255, 255));
        lblSales.setText("Sales Work Area");

        BtnViewSupplierReport.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        BtnViewSupplierReport.setText("View Supplier Report");
        BtnViewSupplierReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewSupplierReportActionPerformed(evt);
            }
        });

        BtnViewCustomerReport.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        BtnViewCustomerReport.setText("View Customer Report");
        BtnViewCustomerReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewCustomerReportActionPerformed(evt);
            }
        });

        BtnViewRevenueReport.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        BtnViewRevenueReport.setText("View Revenue Report");
        BtnViewRevenueReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewRevenueReportActionPerformed(evt);
            }
        });

        BtnManagePrice.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        BtnManagePrice.setText("Manage Price");
        BtnManagePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManagePriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSales)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnViewRevenueReport, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnViewSupplierReport, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnViewCustomerReport, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnManagePrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lblSales)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnViewCustomerReport, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnViewSupplierReport, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnViewRevenueReport, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnManagePrice, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(300, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnViewSupplierReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewSupplierReportActionPerformed
        // TODO add your handling code here:
        ViewSupplierReportJPanel vsrjp = new ViewSupplierReportJPanel(business, userProcessContainer);
        userProcessContainer.add("ViewSupplierReportJPanel",vsrjp);
        ((java.awt.CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_BtnViewSupplierReportActionPerformed

    private void BtnViewCustomerReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewCustomerReportActionPerformed
        // TODO add your handling code here:
        ViewCustomerReportJPanel vcrjp = new ViewCustomerReportJPanel(business, userProcessContainer);
        userProcessContainer.add("ViewCustomerReportJPanel",vcrjp);
        ((java.awt.CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_BtnViewCustomerReportActionPerformed

    private void BtnViewRevenueReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewRevenueReportActionPerformed
        // TODO add your handling code here:
        ViewRevenueReportJPanel vrrjp = new ViewRevenueReportJPanel(business, userProcessContainer);
        userProcessContainer.add("ViewRevenueReportJPanel",vrrjp);
        ((java.awt.CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_BtnViewRevenueReportActionPerformed

    private void BtnManagePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManagePriceActionPerformed
        // TODO add your handling code here:
        ManagePriceJPanel mpjp = new ManagePriceJPanel(business, userProcessContainer);
        userProcessContainer.add("ManagePriceJPanel",mpjp);
        ((java.awt.CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_BtnManagePriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnManagePrice;
    private javax.swing.JButton BtnViewCustomerReport;
    private javax.swing.JButton BtnViewRevenueReport;
    private javax.swing.JButton BtnViewSupplierReport;
    private javax.swing.JLabel lblSales;
    // End of variables declaration//GEN-END:variables
}
